name "publish repo"

on:
   push:
      branches:
        - master


jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: chectout
        uses: actions/checkout@2.1.1
      - name: node
        uses: actions/setup-node@1.4.0
        with:
          node-verison: 12
          registry-url: https://registry.npmjs.org
      - name: publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
